apiVersion: v1
data:
  app.environment: openshift
  app.message: Hello from OpenShift!
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"app.environment":"openshift","app.message":"Hello
      from OpenShift!"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"sample-app"},"name":"sample-app-config","namespace":"nextjs-sample"}}

      '
  labels:
    app: sample-app
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:app.environment: {}
        f:app.message: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: '2025-11-20T04:15:08+00:00'
  name: sample-app-config
  namespace: nextjs-sample
