apiVersion: v1
imagePullSecrets:
- name: builder-dockercfg-jxgfl
kind: ServiceAccount
metadata:
  annotations: {}
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:imagePullSecrets: {}
      f:metadata:
        f:annotations:
          f:openshift.io/internal-registry-pull-secret-ref: {}
      f:secrets:
        k:{"name":"builder-dockercfg-jxgfl"}: {}
    manager: openshift.io/image-registry-pull-secrets_service-account-controller
    operation: Apply
    time: '2025-11-20T04:15:06+00:00'
  name: builder
  namespace: nextjs-sample
secrets:
- name: builder-dockercfg-jxgfl
---
apiVersion: v1
imagePullSecrets:
- name: default-dockercfg-jcgkp
kind: ServiceAccount
metadata:
  annotations: {}
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:imagePullSecrets: {}
      f:metadata:
        f:annotations:
          f:openshift.io/internal-registry-pull-secret-ref: {}
      f:secrets:
        k:{"name":"default-dockercfg-jcgkp"}: {}
    manager: openshift.io/image-registry-pull-secrets_service-account-controller
    operation: Apply
    time: '2025-11-20T04:15:06+00:00'
  name: default
  namespace: nextjs-sample
secrets:
- name: default-dockercfg-jcgkp
---
apiVersion: v1
imagePullSecrets:
- name: deployer-dockercfg-f7lx6
kind: ServiceAccount
metadata:
  annotations: {}
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:imagePullSecrets: {}
      f:metadata:
        f:annotations:
          f:openshift.io/internal-registry-pull-secret-ref: {}
      f:secrets:
        k:{"name":"deployer-dockercfg-f7lx6"}: {}
    manager: openshift.io/image-registry-pull-secrets_service-account-controller
    operation: Apply
    time: '2025-11-20T04:15:06+00:00'
  name: deployer
  namespace: nextjs-sample
secrets:
- name: deployer-dockercfg-f7lx6
