apiVersion: v1
kind: Service
metadata:
  name: nextjs-sample
  labels:
    app: nextjs-sample
spec:
  selector:
    app: nextjs-sample
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP

