apiVersion: v1
imagePullSecrets:
- name: builder-dockercfg-jxgfl
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: builder-dockercfg-jxgfl
  creationTimestamp: '2025-11-20T04:15:06+00:00'
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:imagePullSecrets: {}
      f:metadata:
        f:annotations:
          f:openshift.io/internal-registry-pull-secret-ref: {}
      f:secrets:
        k:{"name":"builder-dockercfg-jxgfl"}: {}
    manager: openshift.io/image-registry-pull-secrets_service-account-controller
    operation: Apply
    time: '2025-11-20T04:15:06+00:00'
  name: builder
  namespace: nextjs-sample
  resourceVersion: '97907'
  uid: 3491729f-c09c-433a-9f58-0db63699722a
secrets:
- name: builder-dockercfg-jxgfl
---
apiVersion: v1
imagePullSecrets:
- name: default-dockercfg-jcgkp
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: default-dockercfg-jcgkp
  creationTimestamp: '2025-11-20T04:15:06+00:00'
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:imagePullSecrets: {}
      f:metadata:
        f:annotations:
          f:openshift.io/internal-registry-pull-secret-ref: {}
      f:secrets:
        k:{"name":"default-dockercfg-jcgkp"}: {}
    manager: openshift.io/image-registry-pull-secrets_service-account-controller
    operation: Apply
    time: '2025-11-20T04:15:06+00:00'
  name: default
  namespace: nextjs-sample
  resourceVersion: '97908'
  uid: 06da6a28-98f9-4795-bdee-55654dde82f8
secrets:
- name: default-dockercfg-jcgkp
---
apiVersion: v1
imagePullSecrets:
- name: deployer-dockercfg-f7lx6
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: deployer-dockercfg-f7lx6
  creationTimestamp: '2025-11-20T04:15:06+00:00'
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:imagePullSecrets: {}
      f:metadata:
        f:annotations:
          f:openshift.io/internal-registry-pull-secret-ref: {}
      f:secrets:
        k:{"name":"deployer-dockercfg-f7lx6"}: {}
    manager: openshift.io/image-registry-pull-secrets_service-account-controller
    operation: Apply
    time: '2025-11-20T04:15:06+00:00'
  name: deployer
  namespace: nextjs-sample
  resourceVersion: '97910'
  uid: 6f71ec3e-9c8e-4a39-9254-1fe2cc149b1e
secrets:
- name: deployer-dockercfg-f7lx6
